articulo/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('parametros/', views.ListCategoriasView.as_view(), name='parametros'),
    path('categoria/list/data/', views.CategoriaListJson.as_view(), name='categoria-list'),
    path('categoria/create', views.CreateCategoriaView.as_view(), name='categoria-create'),
    path('categoria/edit/<pk>/', views.EditCategoriaView.as_view(), name='categoria-edit'),    
    path('unidad/list/data/', views.UnidadListJson.as_view(), name='unidad-list'),
    path('unidad/create', views.CreateUnidadView.as_view(), name='unidad-create'),
    path('unidad/edit/<pk>/', views.EditUnidadView.as_view(), name='unidad-edit'),
    path('', views.ArticulosView.as_view(), name='articulos'),
    path('create/', views.CreateArticuloView.as_view(), name='articulo-create'),
    path('edit/<pk>/', views.EditArticuloView.as_view(), name='articulo-edit'),
    path('list/data/', views.ArticuloListJson.as_view(), name='articulo-list'),
    path('almacen/', views.AlmacenView.as_view(), name='almacenes'),
    path('almacen/create/', views.CreateAlmacenView.as_view(), name='almacen-create'),
    path('almacen/edit/<pk>/', views.EditAlmacenView.as_view(), name='almacen-edit'),
    path('almacen/list/data/', views.AlmacenListJson.as_view(), name='almacen-list'),
    path('almacen/detail/<pk>/', views.DetailAlmacenView.as_view(), name='almacen-detail'),
]

user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('user/list/', views.ListUsersView.as_view(), name='user-list'),
    path('user/list/data/', views.UserListJson.as_view(), name='user-list-json'),    
    path('user/create/', views.CreateUserView.as_view(), name='user-create'),
    path('user/edit/<pk>/', views.EditUserView.as_view(), name='user-edit'),
]

articulo/models.py
import uuid

from django.db import models
from django.utils import timezone

from user.models import User

# Create your models here.
class Unidad(models.Model):
    id = models.UUIDField(primary_key=True,
                          default=uuid.uuid4,
                          editable=False)
    nombre_completo = models.CharField(max_length=100)
    nombre_corto = models.CharField(max_length=10)
    deleted = models.BooleanField(default=False)
    
    created = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User,
                             on_delete=models.SET_NULL,
                             null=True,
                             blank=True)
    
    def __str__(self):
        return f'{self.nombre_completo} - {self.nombre_corto}'
    
    
class Categoria(models.Model):
    id = models.UUIDField(primary_key=True,
                          default=uuid.uuid4,
                          editable=False)
    codigo = models.CharField(max_length=20, unique=True)
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True,
                                   null=True)
    deleted = models.BooleanField(default=False)
    created = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User,
                             on_delete=models.SET_NULL,
                             null=True,
                             blank=True)
    

class Articulo(models.Model):
    id = models.UUIDField(primary_key=True,
                          default=uuid.uuid4,
                          editable=False)
    codigo = models.CharField(max_length=20, unique=True)
    nombre = models.CharField(max_length=300)
    unidad = models.ForeignKey(Unidad,
                               on_delete=models.CASCADE)
    numero_parte = models.CharField(max_length=50)
    deleted = models.BooleanField(default=False)
    
    created = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User,
                             on_delete=models.SET_NULL,
                             null=True,
                             blank=True)
    
    
class Almacen(models.Model):
    id = models.UUIDField(primary_key=True,
                          default=uuid.uuid4,
                          editable=False)
    codigo = models.CharField(max_length=20, unique=True)
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True,
                                   null=True)
    deleted = models.BooleanField(default=False)
    created = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User,
                             on_delete=models.SET_NULL,
                             null=True,
                             blank=True)
    
class AlmacenArticulo(models.Model):
    id = models.UUIDField(primary_key=True,
                          default=uuid.uuid4,
                          editable=False)
    almacen = models.ForeignKey(Almacen, on_delete=models.CASCADE)
    categoria =models.ForeignKey(Categoria, on_delete=models.CASCADE)
    
    deleted = models.BooleanField(default=False)
    created = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User,
                             related_name='user',
                             on_delete=models.SET_NULL,
                             null=True,
                             blank=True)
    updated = models.DateTimeField(blank=True, null=True)
    user_updated = models.ForeignKey(User,
                                     related_name='user_updated',
                                     on_delete=models.SET_NULL,
                                     null=True,
                                     blank=True)

articulo/forms.py
from django import forms
from django.forms import ModelForm, widgets

from articulo.models import Almacen, Articulo, Categoria, Unidad

class CategoriaCreateForm(ModelForm):
    class Meta:
        model = Categoria
        fields = ['codigo', 'nombre', 'descripcion']
        widgets = {
            'codigo': forms.TextInput(attrs={'class': 'form-control'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
        }


class UnidadCreateForm(ModelForm):
    class Meta:
        model = Unidad
        fields = ['nombre_completo', 'nombre_corto']
        widgets = {
            'nombre_completo': forms.TextInput(attrs={'class': 'form-control'}),
            'nombre_corto': forms.TextInput(attrs={'class': 'form-control'}),            
        }     
        
        
class ArticuloCreateForm(ModelForm):
    class Meta:
        model = Articulo
        fields = ['codigo', 'nombre', 'unidad', 'numero_parte']
        widgets = {
            'codigo': forms.TextInput(attrs={'class': 'form-control'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'unidad': forms.Select(attrs={'class': 'form-control'}),
            'numero_parte': forms.TextInput(attrs={'class': 'form-control'}),
        }
        
class AlmacenCreateForm(ModelForm):
    class Meta:
        model = Almacen
        fields = ['codigo', 'nombre', 'descripcion']
        widgets = {
            'codigo': forms.TextInput(attrs={'class': 'form-control'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
        }

articulo/views.py
from django.db.models import Q
from django.http.response import JsonResponse
from django.views.generic import FormView, TemplateView
from django.urls import reverse
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView

from django_datatables_view.base_datatable_view import BaseDatatableView
from django.utils.html import escape

from articulo.forms import AlmacenCreateForm, ArticuloCreateForm, CategoriaCreateForm, UnidadCreateForm

from articulo.models import Almacen, Articulo, Unidad, Categoria
from user.models import User


class ListCategoriasView(TemplateView):    
    template_name = 'categoria/index.html'


class CategoriaListJson(BaseDatatableView):
    model = Categoria        
    order_columns = ['codigo', 'nombre', 'descripcion']
    max_display_length = 50    
    
    def filter_queryset(self, qs):
        search = self.request.GET.get('search[value]', None)
        if search:
            qs = qs.filter(Q(codigo__contains=search)|Q(nombre__contains=search)|Q(descripcion__contains=search))
        return qs    

    def prepare_results(self, qs):
        # prepare list with output column data
        # queryset is already paginated here
        json_data = []
        for item in qs:
            json_data.append([
                escape(item.codigo),
                escape(item.nombre),
                escape(item.descripcion),                
                '<span class="options"><i data-url="{}" class="fas fa-edit"></i><i data-url="{}" class="{}"></i></span>'.format(
                    reverse('categoria-edit', args=[item.id]),
                    '',
                    'fas fa-trash' if not item.deleted else 'fas fa-check'
                    )
            ])
        return json_data 

class CreateCategoriaView(FormView):
    template_name = 'categoria/create.html'
    form_class = CategoriaCreateForm    
    
    def form_valid(self, form):
        form = form.save(commit=False)
        form.user = User.objects.get(pk=self.request.user.id)
        form.save()
        return JsonResponse({'status': 200, 'message': 'Categoria Registrada con exito'})


class EditCategoriaView(UpdateView):
    template_name = 'categoria/edit.html'
    form_class = CategoriaCreateForm
    model = Categoria
    
    def form_valid(self, form):
        form.save()
        return JsonResponse({'status': 200, 'message': 'Categoria Editada con exito'})

class UnidadListJson(BaseDatatableView):
    model = Unidad    
    order_columns = ['nombre_completo', 'nombre_corto']
    max_display_length = 50    
    
    def filter_queryset(self, qs):
        search = self.request.GET.get('search[value]', None)
        if search:
            qs = qs.filter(Q(nombre_completo__contains=search)|Q(nombre_corto__contains=search))
        return qs
    
    def prepare_results(self, qs):
        # prepare list with output column data
        # queryset is already paginated here
        json_data = []
        for item in qs:
            json_data.append([
                escape(item.nombre_completo),
                escape(item.nombre_corto),                
                '<span class="options"><i data-url="{}" class="fas fa-edit"></i><i data-url="{}" class="{}"></i></span>'.format(
                    reverse('unidad-edit', args=[item.id]),
                    '',
                    'fas fa-trash' if not item.deleted else 'fas fa-check'
                    )
            ])
        return json_data
    
class CreateUnidadView(FormView):
    template_name = 'unidad/create.html'
    form_class = UnidadCreateForm    
    
    def form_valid(self, form):
        form = form.save(commit=False)
        form.user = User.objects.get(pk=self.request.user.id)
        form.save()
        return JsonResponse({'status': 200, 'message': 'Unidad Registrada con exito'})
    
class EditUnidadView(UpdateView):
    template_name = 'unidad/edit.html'
    form_class = UnidadCreateForm
    model = Unidad
    
    def form_valid(self, form):
        form.save()
        return JsonResponse({'status': 200, 'message': 'Unidad Editada con exito'})    

class ArticulosView(TemplateView):
    template_name = 'articulo/index.html'
    

class ArticuloListJson(BaseDatatableView):
    model = Articulo    
    order_columns = ['codigo', 'nombre', 'unidad','numero_parte']
    max_display_length = 50    
    
    def filter_queryset(self, qs):
        search = self.request.GET.get('search[value]', None)
        if search:
            qs = qs.filter(Q(codigo__contains=search)|Q(nombre__contains=search)|Q(unidad__contains=search)|Q(numero_parte__contains=search))
        return qs
    
    def prepare_results(self, qs):
        # prepare list with output column data
        # queryset is already paginated here
        json_data = []
        for item in qs:
            json_data.append([
                escape(item.codigo),
                escape(item.nombre),
                escape(item.unidad),
                escape(item.numero_parte),
                '<span class="options"><i data-url="{}" class="fas fa-edit"></i><i data-url="{}" class="{}"></i></span>'.format(
                    reverse('articulo-edit', args=[item.id]),
                    '',
                    'fas fa-trash' if not item.deleted else 'fas fa-check'
                    )
            ])
        return json_data


class CreateArticuloView(FormView):
    template_name = 'articulo/create.html'
    form_class = ArticuloCreateForm
    
    def form_valid(self, form):
        form = form.save(commit=False)
        form.user = User.objects.get(pk=self.request.user.id)
        form.save()
        return JsonResponse({'status': 200, 'message': 'Articulo Registrado con exito'})
    
class EditArticuloView(UpdateView):
    template_name = 'articulo/edit.html'
    form_class = ArticuloCreateForm
    model = Articulo
    
    def form_valid(self, form):
        form.save()
        return JsonResponse({'status': 200, 'message': 'Articulo Editado con exito'})
    
class AlmacenView(TemplateView):
    template_name = 'almacen/index.html'
    

class AlmacenListJson(BaseDatatableView):
    model = Almacen    
    order_columns = ['codigo', 'nombre', 'descripcion']
    max_display_length = 50    
    
    def filter_queryset(self, qs):
        search = self.request.GET.get('search[value]', None)
        if search:
            qs = qs.filter(Q(codigo__contains=search)|Q(nombre__contains=search)|Q(descripcion__contains=search))
        return qs
    
    def prepare_results(self, qs):
        # prepare list with output column data
        # queryset is already paginated here
        json_data = []
        for item in qs:
            json_data.append([
                escape(item.codigo),
                escape(item.nombre),
                escape(item.descripcion),                
                '<span class="options"><a href="{}"><i class="fas fa-eye"></i></a><i data-url="{}" class="fas fa-edit"></i><i data-url="{}" class="{}"></i></span>'.format(
                    reverse('almacen-detail', args=[item.id]),
                    reverse('almacen-edit', args=[item.id]),
                    '',
                    'fas fa-trash' if not item.deleted else 'fas fa-check'
                    )
            ])
        return json_data


class CreateAlmacenView(FormView):
    template_name = 'almacen/create.html'
    form_class = AlmacenCreateForm
    
    def form_valid(self, form):
        form = form.save(commit=False)
        form.user = User.objects.get(pk=self.request.user.id)
        form.save()
        return JsonResponse({'status': 200, 'message': 'Almacen Registrado con exito'})
    
class EditAlmacenView(UpdateView):
    template_name = 'almacen/edit.html'
    form_class = AlmacenCreateForm
    model = Almacen
    
    def form_valid(self, form):
        form.save()
        return JsonResponse({'status': 200, 'message': 'Almacen Editado con exito'})
    
class DetailAlmacenView(DetailView):
    template_name = 'almacen/detail.html'
    model = Almacen

articulo/templates/articulo/create.html
<form class="app-form row" method="post" action="{% url 'articulo-create' %}">
    <h5>Registrar Articulo</h5>
    <div class="input-field col m6 s12">
        {{ form.codigo }}
        <label for="id_codigo">Codigo</label>
    </div>
    <div class="input-field col m6 s12">
        {{ form.nombre }}
        <label for="id_nombre">Nombre</label>
    </div>
    <div class="input-field col m6 s12">
        {{ form.unidad }}
        <label for="id_unidad">Unidad</label>
    </div>
    <div class="input-field col m6 s12">
        {{ form.numero_parte }}
        <label for="id_numero_parte">Numero Parte</label>
    </div>
  </div>
    {% csrf_token %}
    <div class="col s12 display-flex justify-content-end mt-3">
        <button type="submit" class="btn indigo mr-1">Guardar</button>
        <button type="button" class="modal-action modal-close btn btn-light">Cancelar</button>
    </div>
</form>

articulo/templates/articulo/edit.html
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Editar Articulo</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<div class="modal-body">
    <form class="row" action="{% url 'articulo-edit' pk=object.id %}" method="post">        
        <div class="form-group col-md-6">
            <label for="id_codigo">Codigo</label>
            {{ form.codigo }}            
        </div>
        <div class="form-group col-md-6">
            <label for="id_nombre">Nombre</label>
            {{ form.nombre }}
        </div>        
        <div class="form-group col-md-6">
            <label for="id_unidad">Unidad</label>
            {{ form.unidad }}
        </div>
        <div class="form-group col-md-6">
            <label for="id_numero_parte">Numero Parte</label>
            {{ form.numero_parte }}
        </div>
        <div class="col-sm-12 text-right">            
            <button type="submit" class="btn btn-primary">Guardar</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        </div>
        {% csrf_token %}
    </form>                                                            
</div>

articulo/templates/articulo/index.html
{% extends 'base.html' %}

{% load static %}


{% block title %}
    Articulos
{% endblock title %}

{% block vendorcss %}
    <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
{% endblock vendorcss %}

{% block pagecss %}
    
{% endblock pagecss %}

{% block mainbody %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Articulos</h1>
                </div>                
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li><button id="btn-articulo-create" data-url={% url 'articulo-create' %} type="button" class="btn btn-primary btn-block"><i class="fas fa-plus"></i></button></li>                    
                    </ol>
                </div>
            </div>            
        </div><!-- /.container-fluid -->
    </section>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <table id="datatable-articulo" class="table table-bordered table-hover display" data-url="{% url 'articulo-list' %}">
                                <thead>
                                    <tr>
                                        <th>Codigo</th>
                                        <th>Nombre</th>
                                        <th>Unidad</th>
                                        <th>Numero Parte</th>
                                        <th></th>
                                </thead>                                            
                                <tfoot>
                                    <tr>
                                        <th>Codigo</th>
                                        <th>Nombre</th>
                                        <th>Unidad</th>
                                        <th>Numero Parte</th>
                                        <th></th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock mainbody %}

{% block vendorjs %}
    <!-- DataTables  & Plugins -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
{% endblock vendorjs %}

{% block pagejs %}
    <script src="{% static 'app/js/pages/articulo/index.js' %}"></script>
{% endblock pagejs%}