user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('user/list/', views.ListUsersView.as_view(), name='user-list'),
    path('user/list/data/', views.UserListJson.as_view(), name='user-list-json'),    
    path('user/create/', views.CreateUserView.as_view(), name='user-create'),
    path('user/edit/<pk>/', views.EditUserView.as_view(), name='user-edit'),
]

user/models.py
import uuid

from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import gettext_lazy as _
from django.utils import timezone

TIPO_ROL = (
    ('GERENTE', 'GERENTE'),
    ('ADMINISTRACION', 'ADMINISTRACION'),    
)

class CustomUserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    def _create_user(self, email, password=None, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

class User(AbstractUser):
    id = models.UUIDField(primary_key=True,
                          default=uuid.uuid4,
                          editable=False)
    photo = models.ImageField(upload_to='users/photos/',
                              null=True,
                              blank=True)
    username = None
    email = models.EmailField(_('email address'),
                              unique=True)
    telefono = models.CharField(max_length=20,
                                null=True,
                                blank=True)
    document_number = models.CharField(max_length=20, null=True, blank=True)
    birthday = models.DateField(default=timezone.now)
    rol = models.CharField(max_length=30, choices=TIPO_ROL, default='GERENTE')
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(default=timezone.now)    
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    
    objects = CustomUserManager()
    
    def __str__(self):
        return self.email

user/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'rol', 'password1', 'password2', 'first_name',
                  'last_name', 'document_number', 'birthday','telefono')
        widgets = {
            'rol': forms.Select(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'document_number': forms.TextInput(attrs={'class': 'form-control'}),
            'birthday': forms.DateInput(attrs={'class': 'form-control'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control'}),            
        }
        
class UserEditForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'rol', 'first_name','last_name', 'document_number',
                  'birthday','telefono')
        widgets = {
            'rol': forms.Select(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),            
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'document_number': forms.TextInput(attrs={'class': 'form-control'}),
            'birthday': forms.DateInput(attrs={'class': 'form-control'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control'}),            
        }

user/views.py
from django.contrib.auth import get_user_model
from django.db.models import Q
from django.http.response import JsonResponse
from django.views.generic import FormView, TemplateView, ListView, UpdateView

from django_datatables_view.base_datatable_view import BaseDatatableView
from django.utils.html import escape

from django.urls import reverse

from .forms import UserCreateForm, UserEditForm
from .models import User

class HomeView(TemplateView):
    template_name = 'home/index.html'


class ListUsersView(ListView):
    model = User
    template_name = 'user/index.html'
    
class UserListJson(BaseDatatableView):
    model = User    
    order_columns = ['email', 'rol', 'first_name', 'last_name', 'document_number', 'birthday','telefono']
    max_display_length = 50    
    
    def filter_queryset(self, qs):
        search = self.request.GET.get('search[value]', None)
        if search:
            qs = qs.filter(Q(email__contains=search)|Q(rol__contains=search)|Q(first_name__contains=search)|
                           Q(last_name__contains=search)|Q(document_number__contains=search))
        return qs
    
    def prepare_results(self, qs):
        # prepare list with output column data
        # queryset is already paginated here
        json_data = []
        for item in qs:
            json_data.append([
                escape(item.email),
                escape(item.rol),
                escape(item.first_name),
                escape(item.last_name),
                escape(item.document_number),
                item.birthday.strftime("%d-%m-%Y"),
                item.telefono,
                '<span class="options"><i data-url="{}" class="fas fa-edit"></i><i data-url="{}" class="{}"></i></span>'.format(
                    reverse('user-edit', args=[item.id]),
                    '',
                    'fas fa-trash' if item.is_active else 'fas fa-check'
                    )
            ])
        return json_data 
    
class CreateUserView(FormView):
    template_name = 'user/create.html'
    form_class = UserCreateForm    
    
    def form_valid(self, form):
        form.save()
        return JsonResponse({'status': 200, 'message': 'Usuario Registrado con exito'})
    
class EditUserView(UpdateView):
    template_name = 'user/edit.html'
    form_class = UserEditForm
    model = get_user_model()  
    
    def form_valid(self, form):
        form.save()
        return JsonResponse({'status': 200, 'message': 'Usuario Editado con exito'})

user/templates/user/create.html
{% load static %}

<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Registrar Usuario</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<div class="modal-body">
    <form class="row" action="{% url 'user-create' %}" method="post">        
        <div class="form-group col-sm-12 col-md-12">
            <label for="id_email">Rol</label>
            {{ form.rol }}            
        </div>
        <div class="form-group col-sm-12 col-md-12">
            <label for="id_email">Direccion de correo electronico</label>
            {{ form.email }}
        </div>
        <div class="form-group col-sm-12 col-md-12">
            <label for="id_password1">Contraseña</label>
            <input class="form-control" name="password1" required type="password"/>
        </div>
        <div class="form-group col-sm-12 col-md-12">
            <label for="id_password2">Repetir Contraseña</label>
            <input class="form-control" name="password2" required type="password"/>
        </div>                  
        <div class="col-12">
            <small class="form-text text-muted">
                {{ form.password1.help_text }}
            </small>
        </div>                  
        <hr class="col-12" />
        <div class="form-group col-sm-12 col-md-12">
            <label for="id_first_name">Nombres</label>
            {{ form.first_name }}
        </div>
        <div class="form-group col-sm-12 col-md-6">
            <label for="id_last_name">Apellidos</label>
            {{ form.last_name }}
        </div>
        <div class="form-group col-sm-12 col-md-6">
            <label for="id_document_number">Numero Documento</label>
            {{ form.document_number }}
        </div>
        <div class="form-group col-sm-12 col-md-6">
            <label for="id_birthday">Fecha Nacimiento</label>
            {{ form.birthday }}
        </div>
        <div class="form-group col-sm-12 col-md-6">
            <label for="id_telefono">Telefono</label>
            {{ form.telefono }}
        </div>
        <div class="col-sm-12 text-right">            
            <button type="submit" class="btn btn-primary">Guardar</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        </div>
        {% csrf_token %}
    </form>                                                            
</div>

user/templates/user/edit.html
{% load static %}

<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Editar Usuario</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<div class="modal-body">
    <form class="row" action="{% url 'user-edit' pk=object.id %}" method="post">        
        <div class="form-group col-sm-12 col-md-12">
            <label for="id_email">Rol</label>
            {{ form.rol }}            
        </div>
        <div class="form-group col-sm-12 col-md-12">
            <label for="id_email">Direccion de correo electronico</label>
            {{ form.email }}
        </div>        
        <hr class="col-12" />
        <div class="form-group col-sm-12 col-md-12">
            <label for="id_first_name">Nombres</label>
            {{ form.first_name }}
        </div>
        <div class="form-group col-sm-12 col-md-6">
            <label for="id_last_name">Apellidos</label>
            {{ form.last_name }}
        </div>
        <div class="form-group col-sm-12 col-md-6">
            <label for="id_document_number">Numero Documento</label>
            {{ form.document_number }}
        </div>
        <div class="form-group col-sm-12 col-md-6">
            <label for="id_birthday">Fecha Nacimiento</label>
            {{ form.birthday }}
        </div>
        <div class="form-group col-sm-12 col-md-6">
            <label for="id_telefono">Telefono</label>
            {{ form.telefono }}
        </div>
        <div class="col-sm-12 text-right">            
            <button type="submit" class="btn btn-primary">Guardar</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        </div>
        {% csrf_token %}
    </form>                                                            
</div>

user/templates/user/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Usuarios
{% endblock title %}

{% block vendorcss %}
    <!-- DataTables -->
  <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
{% endblock vendorcss %}

{% block pagelevelcss %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/pages/data-tables.css' %}">
{% endblock pagelevelcss %}

{% block section_title %}
    Usuarios
{% endblock section_title %}

{% block mainbody %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Usuarios</h1>
                </div>                
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li><button id="btn-usuario" data-url={% url 'user-create' %} type="button" class="btn btn-primary btn-block"><i class="fas fa-plus"></i></button></li>                    
                    </ol>
                </div>
            </div>            
        </div><!-- /.container-fluid -->
    </section>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <table id="datatable-usuario" class="table table-bordered table-hover display" style="width:100%" data-url="{% url 'user-list-json' %}">
                                <thead>
                                    <tr>
                                        <th>Usuario</th>
                                        <th>Rol</th>
                                        <th>Nombres</th>
                                        <th>Apellidos</th>
                                        <th>Numero Documento</th>
                                        <th>Fecha Nacimiento</th>
                                        <th>Telefono</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>                                    
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>Usuario</th>
                                        <th>Rol</th>
                                        <th>Nombres</th>
                                        <th>Apellidos</th>
                                        <th>Numero Documento</th>
                                        <th>Fecha Nacimiento</th>
                                        <th>Telefono</th>
                                        <th></th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock mainbody %}

{% block vendorjs %}
    <!-- DataTables  & Plugins -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
{% endblock vendorjs %}

{% block pagejs %}
<script src="{% static 'app/js/pages/user/index.js' %}"></script>
{% endblock pagejs%}